import React, { useState } from 'react';
import { Copy, Check, Sparkles, BrainCircuit } from 'lucide-react';
import { CaptionResponse } from '../types';

interface ResultCardProps {
  data: CaptionResponse;
}

export const ResultCard: React.FC<ResultCardProps> = ({ data }) => {
  const [copiedEng, setCopiedEng] = useState(false);
  const [copiedChi, setCopiedChi] = useState(false);

  const copyToClipboard = (text: string, isEnglish: boolean) => {
    navigator.clipboard.writeText(text);
    if (isEnglish) {
      setCopiedEng(true);
      setTimeout(() => setCopiedEng(false), 2000);
    } else {
      setCopiedChi(true);
      setTimeout(() => setCopiedChi(false), 2000);
    }
  };

  return (
    <div className="w-full space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Reasoning Section */}
      <div className="bg-slate-800/80 border border-slate-700 rounded-xl p-5 shadow-lg backdrop-blur-sm">
        <div className="flex items-center gap-2 mb-3 text-indigo-400">
          <BrainCircuit className="w-5 h-5" />
          <h3 className="font-semibold text-sm tracking-wide uppercase">AI Thinking Process</h3>
        </div>
        <p className="text-slate-300 text-sm leading-relaxed italic border-l-2 border-indigo-500/30 pl-4">
          "{data.reasoning}"
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {/* English Caption */}
        <div className="bg-gradient-to-br from-slate-800 to-slate-900 border border-slate-700 rounded-xl p-6 relative group shadow-xl">
          <div className="absolute top-4 right-4">
            <button 
              onClick={() => copyToClipboard(data.englishCaption, true)}
              className="p-2 hover:bg-slate-700 rounded-lg transition-colors text-slate-400 hover:text-white"
              title="Copy English Caption"
            >
              {copiedEng ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
          <div className="mb-4">
            <span className="text-xs font-bold text-slate-500 tracking-wider uppercase">English Caption</span>
          </div>
          <p className="text-xl text-white font-serif leading-relaxed">
            {data.englishCaption}
          </p>
        </div>

        {/* Chinese Caption */}
        <div className="bg-gradient-to-br from-slate-800 to-slate-900 border border-slate-700 rounded-xl p-6 relative group shadow-xl">
          <div className="absolute top-4 right-4">
            <button 
              onClick={() => copyToClipboard(data.chineseCaption, false)}
              className="p-2 hover:bg-slate-700 rounded-lg transition-colors text-slate-400 hover:text-white"
              title="Copy Chinese Caption"
            >
              {copiedChi ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
          <div className="mb-4">
            <span className="text-xs font-bold text-slate-500 tracking-wider uppercase">Chinese Caption</span>
          </div>
          <p className="text-2xl text-white font-serif leading-relaxed">
            {data.chineseCaption}
          </p>
        </div>
      </div>

      <div className="flex justify-center mt-8">
        <div className="flex items-center gap-2 text-emerald-400 bg-emerald-950/30 px-4 py-2 rounded-full border border-emerald-900/50">
          <Sparkles className="w-4 h-4" />
          <span className="text-sm font-medium">Generated by Gemini 2.5</span>
        </div>
      </div>
    </div>
  );
};